// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:image_service/src/metadata.dart';
import 'package:image_service/src/temporary_upload_token_store.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ImageMetadataAdapter());
    registerAdapter(TokenEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ImageMetadataAdapter());
    registerAdapter(TokenEntryAdapter());
  }
}
