name: image_service_client
description: A client library of the "image service" server
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  dart_mappable: ^4.6.1
  http: ^1.3.0
  meta: ^1.17.0

dev_dependencies:
  build_runner: ^2.9.0
  dart_mappable_builder: ^4.6.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
